### ISSUE TITLE
Add feature to update registries without updating package

### ISSUE THREAD

**Issue by lukaszett** [mdomke/schwifty#146]
I'm not sure how I would implement this, so this is just a shot in the dark: It may be desirable to update the registries without having to update the whole package for compatibility reasons.

**Comment by mdomke** [comment]
That would require to load the registry data from elsewhere at runtime, which can have all kinds of undesirable side effects. Another idea might be to have the data in a separate package, which is then required by `schwifty`. But in general, I think it is desirable to have some control over the data that is being used, so that having it colocated with the code is not a bad idea.
