### ISSUE TITLE
Honduras is missing from iban_registry

### ISSUE THREAD

**Issue by jamesuejio** [mdomke/schwifty#69]
Hi all,

Thank you so much for creating this library, it is very helpful. I wanted to create an issue and flag that Honduras does not exist in the iban registry or in the attached PDF that someone linked on another issue. Honduras has a valid IBAN according to https://www.iban.com/structure so I'm wondering how ya'll populate iban_registry and if there is something missing there. Thanks!

[swift_iban_registry.pdf](https://github.com/mdomke/schwifty/files/7661340/swift_iban_registry.pdf)

**Comment by mdomke** [comment]
I'm parsing the IBAN structure from the officially provided data from SWIFT, where Honduras is currently not available. On the site you linked, Honduras is listed under experimental. It would certainly be possible to add a corresponding entry to [schwifty/iban_registry/overwrite.json](https://github.com/mdomke/schwifty/blob/master/schwifty/iban_registry/overwrite.json) in order to support Honduras. Feel free to create a corresponding pull request!

**Comment by jamesuejio** [comment]
Thank you for the response! Honduras has not become a priority for us but I will revisit when it becomes one. Feel free to close this unless you feel like having it open for visibility will be better :)

**Comment by mdomke** [comment]
Many of the "aspirational" SWIFT countries have been added in release `2024.1.1.post0`. Honduras should be among them.
